# Generated by Django 3.1.5 on 2021-01-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('verification_code', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('entity', models.BooleanField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from', to='leads.wallets')),
                ('wallet_partner_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to', to='leads.wallets')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisite', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.services')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.operations')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leads.transactions')),
            ],
        ),
    ]
