# Generated by Django 3.1.5 on 2021-01-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histories',
            old_name='operation_id',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='histories',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='operations',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='operations',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='wallet_id',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='wallet_id',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='wallet_partner_id',
            new_name='wallet_partner',
        ),
        migrations.RenameField(
            model_name='wallets',
            old_name='client_id',
            new_name='client',
        ),
    ]
